In [2]:
import torch
print(torch.__version__)

1.9.0


In [5]:
torch.get_default_dtype(torch.int)
# For Torch only floating point are supported.

TypeError: get_default_dtype() takes no arguments (1 given)

In [7]:
# We can change the default datatype for all of torch to be float 64
torch.set_default_dtype(torch.float64)

Torch Supports 8 CPU and 8 GPU Tensor types. These datatype support different sizes of float integer and bytes.

In [11]:
tensor_arr=torch.Tensor([[1,2,3], [4,5,6]])
tensor_arr # Two dimensional list used to instantiate a torch tensor object, for default tensor type i.e. float64

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
torch.is_tensor(tensor_arr) # to check if a particular object is of type tensor

True

In [14]:
torch.numel(tensor_arr) # Print number of elements in a particular tensor no matter what is the size or shape

6

In [20]:
tensor_uninitialized=torch.Tensor(2, 2) # Uninitialized tensor object as we have only specified the shape of tensor

In [24]:
tensor_uninitialized # This means that by default pytorch will allocate the memory for this tensor, 
                     #but won't setup any initial values as we haven't specified any.

tensor([[ 1.7272e-77,  1.7272e-77],
        [1.9763e-323, 4.9407e-324]])

In [25]:
tensor_initialized = torch.rand(2, 2)

In [26]:
tensor_initialized # Torch.rand will initialize a 2x2 tensor here and fill it with the random values.

tensor([[0.5975, 0.2571],
        [0.0300, 0.5153]])

This is a quick and easy way to initialize the weight of your model parameters.

In [28]:
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor) #Integer tensor on CPU.
tensor_int #tensor of a particular type, not the default dtype.

tensor([5, 3], dtype=torch.int32)

To create tensor on GPU, we will have to use different classes. Torch.Cuda.IntTensor is the equivalent for an Integer tensor on GPU.

In [32]:
tensor_short=torch.ShortTensor([1.0, 2.0, 3.0])
tensor_short #Another way to instantiate a tensor of a particular type is to instantiate the type object directly.
             #ShortTensor will create in16 objects'''

<ipython-input-32-a62edd7762f6>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_short=torch.ShortTensor([1.0, 2.0, 3.0])


tensor([1, 2, 3], dtype=torch.int16)

PyTorch also has support for tensors of type torch.half,  this is a floating point tensor which occupies half as much memory for each element as a float 32.

In [34]:
tensor_half_float=torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_half_float

tensor([1., 2., 3.], dtype=torch.float16)

Custom Torch Tensor, that allow us to specify the shape and specify the fill_value for the tensor.

In [35]:
tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

There are some helper methods that can quickly create tensors of a specified shape, filled with common values.

In [38]:
tensor_of_ones=torch.ones([2, 4], dtype=torch.int32)
tensor_of_ones #Torch.ones will give you a tensor of the shape and type specified and filled with all 1s.

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

We can create a tensor based on a existing tensor, of same shape, we can use functions which have the like word within them.

In [40]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [42]:
tensor_eye=torch.eye(5)
tensor_eye #Torch.eye will create two dimensional square matrix, with the main diagonal filled with 1s.

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

For an already instantiated tensor, we can figure out the indices where the non-zero elements lie, we can call the torch.nonzero function.

In [45]:
nonzero=torch.nonzero(tensor_eye)
nonzero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

To make a copy of existing tensor or of some numpy array or list in order to create the tensor, we can use torch.tensor function.

In [47]:
i = torch.tensor([[0,1,1],
                [2,2,0]])
i

tensor([[0, 1, 1],
        [2, 2, 0]])

In [48]:
v=torch.tensor([3, 4, 5], dtype=torch.float32)

PyTorch has support for sparse tensors, commonly used in building ml models. Data may not always be dense, it would be a sparse data, for that we would want a sparse tensor.

In [50]:
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5]) 

The sparse_coo_tensor function constructs a sparse tensor in coordinate format. The non-zero elements are at the indices that we specify, that is 'i' with the given value that is specified, which is variable 'v'. The resulting sparse tensor is of shape 2, 5. 

The tensor 'i' instantiated earlier, specifies the indices at which this sparse tensor contains the data, whereas the tensor v specifies the values contained in the sparse tensor.

In [54]:
sparse_tensor.data #Every PyTorch tensor has data member variable which can be used to access the underlying matrix.

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

The structure and layout is very different from the dense tensors that we have seen. The size of this sparse tensor is (2, 5), this only specified values at index positions for 2 rows and 3 columns <indices tensor>. The remaining two columns in the sparse tensor don't have any values.

We know which index positions have values in the sparse tensors. The values are given by the values tensors here, which means when you see the number 0 within the indices tensor, that orresponds to the values at position 0 from the values tensors

### Simple operations on Tensors

In [57]:
initial_tensor = torch.rand(2, 3)
initial_tensor

tensor([[0.8040, 0.5242, 0.8992],
        [0.9396, 0.6307, 0.5803]])

In [60]:
initial_tensor.fill_(10) #Any tensor func which has underscore as suffix, performs operation in-place.

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [62]:
new_tensor = initial_tensor.add(5)
new_tensor  # Out of place operation, addition to existing tensor and storing the results to a new tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [63]:
initial_tensor.add_(8)
initial_tensor # Add operation in-place

tensor([[18., 18., 18.],
        [18., 18., 18.]])

<b> Add_ </b> is an in-place operation, which updates/modifies the initial tensor itself.

In [66]:
new_tensor.sqrt_()
new_tensor # In-place square root operation.

tensor([[1.4029, 1.4029, 1.4029],
        [1.4029, 1.4029, 1.4029]])

In [69]:
x=torch.linspace(start=0.1, end=10.0, steps=15)
x #will generate 15 evenly spaced numbers between 1 and 10.

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])