In [2]:
import torch
print(torch.__version__)

1.9.0


In [5]:
torch.get_default_dtype(torch.int)
# For Torch only floating point are supported.

TypeError: get_default_dtype() takes no arguments (1 given)

In [7]:
# We can change the default datatype for all of torch to be float 64
torch.set_default_dtype(torch.float64)

Torch Supports 8 CPU and 8 GPU Tensor types. These datatype support different sizes of float integer and bytes.

In [11]:
tensor_arr=torch.Tensor([[1,2,3], [4,5,6]])
tensor_arr # Two dimensional list used to instantiate a torch tensor object, for default tensor type i.e. float64

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
torch.is_tensor(tensor_arr) # to check if a particular object is of type tensor

True

In [14]:
torch.numel(tensor_arr) # Print number of elements in a particular tensor no matter what is the size or shape

6

In [20]:
tensor_uninitialized=torch.Tensor(2, 2) # Uninitialized tensor object as we have only specified the shape of tensor

In [24]:
tensor_uninitialized # This means that by default pytorch will allocate the memory for this tensor, 
                     #but won't setup any initial values as we haven't specified any.

tensor([[ 1.7272e-77,  1.7272e-77],
        [1.9763e-323, 4.9407e-324]])

In [25]:
tensor_initialized = torch.rand(2, 2)

In [26]:
tensor_initialized # Torch.rand will initialize a 2x2 tensor here and fill it with the random values.

tensor([[0.5975, 0.2571],
        [0.0300, 0.5153]])

This is a quick and easy way to initialize the weight of your model parameters.

In [28]:
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor) #Integer tensor on CPU.
tensor_int #tensor of a particular type, not the default dtype.

tensor([5, 3], dtype=torch.int32)

To create tensor on GPU, we will have to use different classes. Torch.Cuda.IntTensor is the equivalent for an Integer tensor on GPU.

In [32]:
tensor_short=torch.ShortTensor([1.0, 2.0, 3.0])
tensor_short #Another way to instantiate a tensor of a particular type is to instantiate the type object directly.
             #ShortTensor will create in16 objects'''

<ipython-input-32-a62edd7762f6>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_short=torch.ShortTensor([1.0, 2.0, 3.0])


tensor([1, 2, 3], dtype=torch.int16)

PyTorch also has support for tensors of type torch.half,  this is a floating point tensor which occupies half as much memory for each element as a float 32.

In [34]:
tensor_half_float=torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_half_float

tensor([1., 2., 3.], dtype=torch.float16)

Custom Torch Tensor, that allow us to specify the shape and specify the fill_value for the tensor.

In [35]:
tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])